emet.sls
Microsoft has deprecated EMET 5.0. It no longer appears available for download, so it has been removed from the package definition.
=> Updated EMET version to 5.1

blender.sls
Updated blender.sls top latest released ver. 2.73a (64-bit) - the old installer had the 32 bit version being installed on the 64-bit win OS.
=> Update blender.sls to ver. 2.73a

chrome.sls
Updated chrome version number to 66.41.32862. but the download URL keeps pointing to the latest version of chrome and the actual installed version number will hence keep going up and up all the time anyway
=> Update chrome.sls to ver. 66.41.32862

gpg4win-light.sls
Created initial gpg4win-light.sls ver. 2.2.3. (Note! This 'light' gpg4win package won't actually be installed by salt, as the upstream folks need to fix the /S silent installer switch first.
=> Create initial gpg4win-light.sls ver. 2.2.3

gpg4win-vanilla.sls
Created initial gpg4win-vanilla.sls ver. 2.2.3 (contains only the GnuPG component)
=> Create initial gpg4win-vanilla.sls ver. 2.2.3

truecrypt.sls
Created initial truecrypt.sls ver. 7.1a. (Note! There is however a issue with the /S instaler switch, until that problem is overcome, it won't be easily installable using salt. I am creating this sls file and will then open up an issue on the faulty installer switch.)
=> Create initial truecrypt.sls ver. 7.1a

audacity.sls
the sourceforge download URLs ending in /download cause salt to create a dl file called download with no suffix and it can't execute or install the files. so I had to take a regional final download link instead of the one that would have geographically distriubuted  the DL to a geographically 'local' link
=> fixed 'broken' download URL

filezilla.sls
sourceforge URLs ending in /download or /download&nowrap don't work for salt at this time
=> corrected 'broken' download URL

fciv.sls
Created initial MS fciv.sls ver. 2.05. Don't really like this way of installing software. dropping it in c:\windows directory. but salt needs to learn to deal with apps that do not have an installer, until then thsi will have to do. plus the fciv.xe is not a dangerous executable prone to exploitation and I do have a tested and working uninstaller for salt , so if salt tries to remove it , that will succeed and put the machine back to how it was.
=> Create initial MS fciv.sls ver. 2.05

gpg4win-light.sls
The 2.2.1 "light" installer has an upstream bug. I added a comment to point to the workaround into the sls file.
=> commented upstream installer bug work-around

curl.sls
Created initial curl ver. 7.40.0
Note 1: You need to download the win64 msi from website (Captcha protected) and place in your winrepo on master
source: http://www.confusedbycode.com/curl/#downloads
Note 2: 'curl' is also a standard powershell alias as of at least .NET 4.0 for Invoke-WebRequest,
so you might not be calling the right 'curl'
=> Create initial curl ver. 7.40.0

irfanview-plugins.sls
Create initial irfanview-plugins.sls ver. 4.38
the plugins do not have an un-installer that I can find. to uninstall them one has to uninstall IrfanView 4.38 itself.
=> Create initial irfanview-plugins.sls ver. 4.38

mysql-installer-community.sls
Created initial mysql-installer-community.sls ver. 1.4.3.0.
This will enable installation of all sorts of constellations of MySQL 5.6.23.0, Developer default, Server Only, Client only, Full and Custom.  
For MySQL Server 5.6.23.0 Community installation instructions read:
https://dev.mysql.com/doc/refman/5.6/en/mysql-installer-gui.html
https://dev.mysql.com/doc/refman/5.6/en/MySQLInstallerConsole.html
=> Create initial mysql-installer-community.sls ver. 1.4.3.0

ultravnc_x86.sls
Renamed old pre-existing ultravnc.sls to ultravnc_x86.sls and updated to ver. 1.2.09, as well as fixing typo in path of ver. 1.1.9.6 uninstaller.
=> Rename ultravnc.sls to ultravnc_x86.sls and update to ver. 1.2.09

curl.sls
curl.sls broke winrepo.genrepo . this fixes issue #149
=> fixed syntax error in curl.sls

ccleaner.sls
fixing syntax of ccleaner.sls blocks were misaligned . this fixes issue #155
=> fixing syntax of ccleaner.sls blocks were misaligned

xampp.sls
xampp.sls was misformatted and broke winrepo.genrepo . This fixes #151
=> fix syntax error - misaligned block in xampp.sls

mysql-installer-community.sls
fixing syntax of misaligned blocks in mysql-installer-community.sls. this fixes issue #153
=> fixing syntax of misaligned blocks in mysql-installer-community.sls

spybot.sls
Created initial spybot.sls ver. 2.4
The un-installer opens up a dialogue and won't proceed, since it is invisible. Logged a bug upstream, but they might not be inclined to 'fix' this.
=> Create initial spybot.sls ver. 2.4

gpu-z.sls
Created initial gpu-z.sls ver. 0.8.1
This installer needs a bit of work. the /S switch will launch it and then the actual installer needs to be laucnhed from it's menu. This will need automating for this to work with salt. But on the flipside the /S for unistall does work.
RFE logged upstream for them to add a properly silent  /S switch to installer.
=> Create initial gpu-z.sls ver. 0.8.1

pgina.sls
The pluggable, open source credential provider for Windows.
Tested on Windows 8 and Windows Server 2012.
I also created a [salt configuration formula for pGina](https://github.com/xetus-oss/salt-win-pgina-formula) that allows configuration of the Local Authentication and LDAP plugins for pGina
=> Adds pGina 3.1.8.0

cdex.sls
Looks like I also removed a newline at the end of the file, but this appears to fix the genrepo failure.
NOTE: This was not tested to see if cdex v1.75 will actually download and run, it just fixes the sls so genrepo does not fail
=> Removes the link after cdex: in line 1 to prevent genrepo from failing

ms-vcpp-2012-redist.sls, ms-vcpp-2012-redist_x86.sls
The packages were installing, but salt was reporting errors. I determined
that it was due to the version and full_name string mismatch from
pkg.list_pkgs
This pull request includes the patch for that. This was tested on 
Windows 8.1 and Windows Server 2012
=> Updates the version and full_name strings for ms-vcpp-2012-redist

salt-minion.sls
Updated salt-minion.sls to ver. 2015.3 and 2015.3-2 and corrected previously published URL for 2015.2-2 that suddenly changed 'back' to 2015.2.
=> Update salt-minion.sls to ver. 2015.3 and 2015.3-2

salt-minion_x86.sls
Updated salt-minion_x86.sls to ver. 2015.5.3 and 2015.5.3-2 and corrected previously published URL for 2015.2-2 that suddenly changed 'back' to 2015.2.
=> Update salt-minion_x86.sls to ver. 2015.5.3 and 2015.5.3-2

gedit.sls
Corrected ver no and full_name of gedit.sls. The add/remove name was wrong, as was sls file version number.
=> Correct ver. no and full_name of gedit.sls

putty.sls
Correct putty.sls windows full_name to use the word windows actually uses 'release' and not the previously present one 'version'
=> Correct putty.sls windows full_name

pdf24creator.sls
Corrected pdf24creator.sls windows full_name, as it was, the package was not being recognised as ever being successfully installed.
=> Correct pdf24creator.sls windows full_name

chrome.sls
Updated chrome.sls ver. 66.77.16516, the old way of un-installing had it's problems. This new way also has limitations. Google only release a single URL and the version can (and does) change failry frequently. Which then means the un-installer GUID will be different. I will endeveour to check this more frequently than in the past.
=> Update chrome.sls ver. 66.77.16516

putty_x86.sls
Cleaned putty_x86.sls remove old versions, no sense in keeping old unsecure versions around.
=> Clean putty_x86.sls remove old versions

pdf24creator.sls
Fixed pdf24creator.sls version number mismatch, software version number and windows installed version numbers were mismatched
=> Fix pdf24creator.sls version number mismatch

windirstat.sls
Fixed windirstat.sls mismatched version number, it did not match windows idea of it's version number
=> Fix windirstat.sls mismatched version number

keepass.sls
Corrected exact version number string for keepass.sls to 1.29.0
=> Correct exact version number string for keepass.sls to 1.29.0

adobereader.sls
Removed Adobe Reader XI from Reader X line. Adobe maintain 3 lines of Reader right now.
Reader DC 2015.008.20082   -> adobereader-dc.sls
Reader 11.0.10                       -> adobereader-xi.sls
Reader 10.1.4                         -> adobereader.sls (this line)
=> Remove Adobe Reader XI from Reader X line

windirstat_x86.sls
Add missing ver number to registry, so that the winrepo installer finds both the full_name AND the version match
=> Add missing ver number to registry

passware-kit-agent.sls
fixed case of passware-kit-agent.sls to all lowercase
@dkarpo dkarpo@gmail.com are you OK with this pkg name to be all lowercased?
=> fix case of passware-kit-agent.sls to all lowercase

passware-kit-forensic.sls
fixed case of passware-kit-forensic pkg to all lowercase
@dkarpo dkarpo@gmail.com are you OK with the pkg name to be all lowercased?
=> fix case of passware-kit-forensic pkg to all lowercase

clink.sls, clink_x86.sls
Updated to have all clink ver 4 releases in this file, want to use it as a sample to add jijnja snippets in, to create a unified winrepo sls that windows salt-minions from Berrilium (>= 2015.8) or higher can interpret in real-time.
=> Update clink ver 4 (all released versions)

snmptools.sls, snmptools_x86.sls
The SnmpTools installer doesn't populate the DisplayVersion, and pkg.version / pkg.list_pkgs reports the version as *Not Found*. Using *Not Found* as the version in the package file seems to work, with the pkg.* execution modules operating normally, and the pkg.installed state module correctly detecting when it's already installed (see [this Gist for an example](https://gist.github.com/m03/4b444666290574795ff7)). If there's a better official way to handle this, I can modify the package files accordingly.
---
SnmpTools is an snmp agent servicing all windows performance counters thus allowing tools such as MRTG or Cacti to retrieve windows performance values (cpu, memory, disk, etc.).
http://labalec.fr/erwan/?page_id=24
=> Create initial snmptools.sls and snmptools_x86.sls

golang.sls, golang_x86.sls
Consider identifying where the installer goes locally and using that rather than downloading uninstaller.
=> Bump golang version offerings to include 1.5

ms-vcpp-2005-sp1-mfc-redist_x64.sls, ms-vcpp-2005-sp1-mfc-redist_x86.sls
Microsoft Visual C++ 2005 Service Pack 1 Redistributable Package MFC Security Update
http://www.microsoft.com/en-us/download/details.aspx?id=26347
The version difference between _x64 and _x86 is intentional.
=> Create initial ms-vcpp-2005-sp1-mfc-redist ver. 8.0.61000

wix-toolset.sls
This download URL does not end in the name of the installer, and therefore the downloaded file can't be executed 'as-is' in this case it downloads a file called '1483377#'
=> Create initial wix-toolset ver. 3.10.0.2103

nsclient.sls
Update the installer/uninstaller URLs for the existing nsclient versions, these recently changed and broke this package sls. I'm choosing not to swap the existing versions to salt:// references since that would be a pretty confusing change for people currently using the formula.
However, I've also added the most recent nsclient version with a salt:// reference. It's much better to force the administrator to locally host the installer than to force them to use a link that is likely to break at some indefinite point in the future. For all new versions going forward, I would strongly recommend doing this.
Fixes #586
=> Fix for #586, NSClient++ URL updates

git.sls, git_x86.sls
ver. 2.6.3 had an installation regression see https://github.com/saltstack/salt-winrepo-ng/issues/142
=> Downgrade git to ver. 2.6.2

icecast.sls, icecast_x86.sls
Icecast is a streaming media server which currently supports Ogg (Vorbis and Theora), Opus, WebM and MP3 audio streams.
http://icecast.org/
=> Create initial icecast.sls 2.4.2

stunnel.sls, stunnel_x86.sls
**Changes**
* Update stunnel to current 5.29 version.
* See https://www.stunnel.org/downloads.html
**Testing**
* Tested on Windows 2012r2 running salt-minion 2015.5.8.
=> Update stunnel to ver. 5.29

cyberduck-cli.sls
Cyberduck for the command line interface (CLI).
https://duck.sh/?l=en
=> Create initial cyberduck-cli.sls 1.0.0.0

salt-minion.sls, salt-minion_x86.sls
Based on @jfindlay comment on saltstack/salt#30931 (comment) I am adding the previously skipped 2015.8.4 release back in to the slat-minon sls file.
=> Re-Add salt-minion ver. 2015.8.4

aspnet-mvc1.sls
ASP.NET MVC 1.0 provides a new Model-View-Controller (MVC) framework on top of the existing ASP.NET 3.5 runtime.
https://www.microsoft.com/en-us/download/details.aspx?id=5388
Tested install on Windows 2012r2 running salt-minion 2015.5.8.
=> Create initial aspnet-mvc1 1.0.0.0

sscserv-free.sls, sscserv-free_x86.sls
SSC Serv is a service for Microsoft Windows, which collects system statistics and submits them to a central statistics server. It is similar to and compatible with collectd, a free and open-sourced solution for UNIX systems.
https://ssc-serv.com/features.shtml
Tested on Windows 2012r2.
=> Create initial SSC Serv Free 3.6.1
