bulk_extractor.sls
Updated download URL for latest ver. 1.5.5
=> Update bulk_extractor.sls to ver. 1.5.5

firefox.sls
Updated download URL for v 35.0.1
=> Update firefox.sls to v 35.0.1

thunderbird.sls
Updated download URL for v. 31.4.0 en-GB x86
=> Update thunderbird.sls to v 31.4.0 en-GB x86

cdroller.sls
Updated download URL for latest ver. 10.0
=> Update cdroller.sls to ver. 10.0

adobereader.sls
Updated Adobe Reader XI URL for v 11.0.10
=> Update adobereader.sls to v. 11.0.10

autopsy.sls
Updated autopsy to latest ver. 3.1.1 and added download URL
=> Update autopsy.sls to ver. 3.1.1

audacity.sls
Updated the download URL for latest ver. 2.0.6
=> Update audacity.sls v 2.0.6

adobeflashplayer.sls, adobeflashplayeractivex.sls, adobeflashplayerplugin.sls, audacity.sls, putty.sls
sorry these three are all jumbled together, can't figure how to use github web to split it into proper separate bite-sizes.
=> updated putty.sls + added initial adobeflashplayerplugin.sls and initial adobeflashplayeractivex.sls

npp.sls
Updated npp.sls download URL for ver. 6.7.4 (je suis charlie - release)
=> Update npp.sls to v. 6.7.4

clamwin.sls
=> Update clamwin.sls to ver 0.98.5

irfanview.sls
updated IrfanView to ver. 4.38 - old '/verysilent' switch did not work for me so testeed and replaced with /silent one instead and added other settings about as explained in comment lines. Un-installer has also changed name and now also needs /silent switch.
=> Update irfanview.sls to ver. 4.38

pdf24creator.sls
Created initial pdf24creator.sls ver. 6.9.2.0
=> Create initial pdf24creator.sls ver. 6.9.2.0

gpg4win.sls
Created initial gpg4win.sls ver. 2.2.3 (contains full gpg4win components)
=> Create initial gpg4win.sls ver. 2.2.3

gnucash.sls
Created initial gnucash.sls ver. 2.6.5. Issue #25 can now be closed.
ping @UtahDave
=> Create initial gnucash.sls ver. 2.6.5

stellarium.sls
Created initial stellarium.sls ver. 0.13.2, Issue #22 can now be closed.
ping @UtahDave
=> Create initial stellarium.sls ver. 0.13.2

cdex.sls
Created initial cdex.sls ver. 1.72. Issue #19 can be closed now.
ping @UtahDave
=> Create initial cdex.sls ver. 1.72

svn.sls
Created initial svn.sls ver. 1.8.11. Issue #6 can now be closed.
ping @UtahDave
=> Create initial svn.sls ver. 1.8.11

inkscape.sls
Created initial inkscape.sls ver. 0.91. Issue #11 can be closed now.
=> Create initial inkscape.sls ver. 0.91

gimp.sls
Created initial gimp.sls ver. 2.8.14
=> Create initial gimp.sls ver. 2.8.14

openoffice.sls
Created initial openoffice.sls ver. 4.1.1
=> Create initial openoffice.sls ver. 4.1.1

libreoffice.sls, vlc.sls, winscp.sls
=> Update vlc.sls to ver. 2.1.5

nsclient.sls
Update nsclient.sls to ver. 0.4.3.88
=> Update nsclient.sls to ver. 0.4.3.88

nxlog.sls
=> Update nxlog to ver. 2.8.1248

pidgin.sls
=> Update pidgin to ver. 2.10.11

gow.sls
Created initial gow.sls ver. 0.8.0
=> Create initial gow.sls ver. 0.8.0

msysgit.sls
Updated msysgit.sls to ver. 1.9.5-preview20141217
=> Update msysgit.sls to ver. 1.9.5-preview20141217

teamviewer.sls
Created initial teamviewer.sls ver. 10.0.38475
=> Create initial teamviewer.sls ver. 10.0.38475

skype-msi.sls
Created initial skype-msi.sls ver. 7.1.0.105
=> Create initial skype-msi.sls ver. 7.1.0.105

ccleaner.sls
Created initial ccleaner.sls ver. 5.02.5101
=> Create initial ccleaner.sls ver. 5.02.5101

defraggler.sls
Created initial defraggler.sls ver. 2.18.945
=> Create initial defraggler.sls ver. 2.18.945

ultradefrag.sls
Created initial ultradefrag.sls ver. 6.0.2
=> Create initial ultradefrag.sls ver. 6.0.2

realvnc.sls
Updated realvnc.sls to ver. 5.2.2
=> Update realvnc.sls to ver. 5.2.2

xampp.sls
Created initial xampp.sls ver. 5.6.3.0. Fixes issue #28
=> Create initial xampp.sls ver. 5.6.3.0

wamp-stack.sls
Created initial wamp-stack.sls ver. 5.4.36.0
(Note: this software needs MS VC++ 2012 redistributable installed first. Will create salt installer for that after this one and create a PR for it.)
=> Create initial wamp-stack.sls ver. 5.4.36.0

wamp-server.sls
Created initial wamp-server.sls ver. 2.5
=> Create initial wamp-server.sls ver. 2.5

ms-vcpp-2012-redist.sls
Created initial ms-vcpp-2012-redist.sls ver. 11.0.61030
the package wamp-stack.sls needs this installed before it will install.
=> Create initial ms-vcpp-2012-redist.sls ver. 11.0.61030

ms-vcpp-2012-redist_x86.sls
Created initial ms-vcpp-2012-redist_x86.sls ver. 11.0.61030
=> Create initial ms-vcpp-2012-redist_x86.sls ver. 11.0.61030

mysql-essential.sls
Created initial mysql-server.sls ver. 5.1.73. Fixes Issue #24
=> Create initial mysql-server.sls ver. 5.1.73

salt-minion.sls
Created initial salt-minion.sls including most historical releases.
=> Create initial salt-minion.sls

ultravnc.sls
Updated ultravnc.sls to ver.  1.2.05 and renamed the old sls file to ultravnc_x86.sls and updated it as well in separate PR
=> Update ultravnc.sls to ver.  1.2.05 and rename old sls file

tightvnc_x86.sls
Created initial tigthvnc_x86.sls ver. 2.7.10.0
=> Create initial tigthvnc_x86.sls ver. 2.7.10.0

tightvnc.sls
Created initial tightvnc.sls ver. 2.7.10.0
=> Create initial tightvnc.sls ver. 2.7.10.0

ultravnc_x86.sls
fixed syntax in ultravnc_x86.sls . this fixes issue #157
=> fixed syntax in ultravnc_x86.sls

software-informer.sls
Created initial software-informer.sls ver. 1.4.1250.0
Note: the un-installer brings up a dialog box but does complete without any user interaction
=> Create initial software-informer.sls ver. 1.4.1250.0

filehippo-app-manager.sls
Created initial filehippo-app-manager.sls ver. 1.47
=> Create initial filehippo-app-manager.sls ver. 1.47

emsisoft-anti-malware.sls
Created initial emsisoft-anti-malware.sls ver. 9.0
=> Create initial emsisoft-anti-malware.sls ver. 9.0

openlp.sls
Created initial openlp.sls ver. 2.0.5
=> Create initial openlp.sls ver. 2.0.5

malwarebytes.sls
Created initial malwarebytes.sls ver. 2.0.4.1028
=> Create initial malwarebytes.sls ver. 2.0.4.1028

secunia.psi.sls
Created initial secunia.psi.sls ver. 3.0.0.10004
=> Create initial secunia.psi.sls ver. 3.0.0.10004

patchmypc-free.sls
Created initial patchmypc-free.sls ver. 3.0.1.1
=> Create initial patchmypc-free.sls ver. 3.0.1.1

win-app-manager.sls
Created initial win-app-manager ver. 15.01.11
=> Create initial win-app-manager ver. 15.01.11

windirstat.sls
Created initial windirstat.sls ver. 1.1.2.80
=> Create initial windirstat.sls ver. 1.1.2.80

handbrake.sls
Created initial handbrake.sls ver. 0.10.0
=> Create initial handbrake.sls ver. 0.10.0

handbrake_x86.sls
Created initial handbrake_x86.sls ver. 0.10.0
=> Create initial handbrake_x86.sls ver. 0.10.0

glarysoft-absolute-uninstaller.sls
Created initial glarysoft-absolute-uninstaller.sls ver. 5.3.1.19
=> Create initial glarysoft-absolute-uninstaller.sls ver. 5.3.1.19

cpu-z.sls
Created initial cpu-z.sls ver. 1.71.1
=> Create initial cpu-z.sls ver. 1.71.1

ms-vcpp-2008-redist.sls
Created initial ms-vcpp-2008-redist.sls ver. 9.0.21022 (MS VC9 runtimes)
=> Create initial ms-vcpp-2008-redist.sls ver. 9.0.21022 (MS VC9 runtimes)

ms-vcpp-2008-redist_x86.sls
Created initial ms-vcpp-2008-redist_x86.sls ver. 9.0.21022 (VC9 runtimes)
=> Create initial ms-vcpp-2008-redist_x86.sls ver. 9.0.21022 (VC9 runtimes)

tortoise-git.sls
Created initial tortoise-git.sls ver. 1.8.13.0
=> Create initial tortoise-git.sls ver. 1.8.13.0

tortoise-git_x86.sls
Created initial tortoise-git_x86.sls ver. 1.8.13.0
=> Create initial tortoise-git_x86.sls ver. 1.8.13.0

tortoise-svn.sls
Created initial tortoise-svn.sls ver. 1.8.10.26129
=> Create initial tortoise-svn.sls ver. 1.8.10.26129

tortoise-svn_x86.sls
Created initial tortoise-svn_x86.sls ver. 1.8.10.26129
=> Create initial tortoise-svn_x86.sls ver. 1.8.10.26129

tortoise-hg.sls
Created initial tortoise-hg.sls ver. 3.3.0
=> Create initial tortoise-hg.sls ver. 3.3.0

tortoise-hg_x86.sls
Created initial tortoise-hg_x86.sls ver. 3.3.0
=> Create initial tortoise-hg_x86.sls ver. 3.3.0

tortoise-bzr.sls
Created initial tortoise-bzr.sls ver. 2.5.1
=> Create initial tortoise-bzr.sls ver. 2.5.1

autohotkey.sls
Created initial autohotkey.sls ver. 1.1.19.03
=> Create initial autohotkey.sls ver. 1.1.19.03

audacity.sls
Update audacity.sls to v. 2.1.0
=> Update audacity.sls to v. 2.1.0

autohotkey.sls
Update autohotkey.sls to v. 1.1.22.01
=> Update autohotkey.sls to v. 1.1.22.01

autopsy.sls
Update autopsy.sls to ver. 3.1.2
=> Update autopsy.sls to ver. 3.1.2

cdex.sls
=> Update cdex.sls to ver. 1.75

firefox.sls
Update firefox.sls to ver. 38.0.1
=> Update firefox.sls to ver. 38.0.1

npp.sls
Update npp.sls to ver. 6.7.8.2
=> Update npp.sls to ver. 6.7.8.2

putty.sls
=> Update putty.sls to ver. 0.64

winscp.sls
Update winscp.sls to ver. 5.7.3
=> Update winscp.sls to ver. 5.7.3

thunderbird.sls
Update thunderbird.sls to ver. 31.7.0
=> Update thunderbird.sls to ver. 31.7.0

ccleaner.sls
Update ccleaner.sls to ver. 5.06
=> Update ccleaner.sls to ver. 5.06

blender.sls
=> Update blender.sls ver. 2.74

awscli_x64.sls, awscli_x86.sls
Add formulas to install aws cli
http://aws.amazon.com/cli/
=> Add formulas for aws-cli

salt-minion_x86.sls
Updated salt-minion_x86.sls to Salt Minion v2015.5.1-3
=> Update salt-minion_x86.sls to v2015.5.1-3

salt-minion.sls
Update salt-minion.sls to Salt Minion v2015.5.1-3
=> Update salt-minion.sls to v2015.5.1-3

clamwin.sls
Updated clamwin.sls to ver. 0.98.6
=> Update clamwin.sls to ver. 0.98.6

thunderbird.sls
Updated thunderbird.sls to ver. 38.0.1
=> Update thunderbird.sls to ver. 38.0.1

salt-minion.sls
Updated salt-minion.sls to Salt Minion v2015.5.2-2
=> Update salt-minion.sls to v2015.5.2-2

salt-minion_x86.sls
Updated salt-minion_x86.sls to Salt Minion v2015.5.2-2
=> Update salt-minion_x86.sls to v2015.5.2-2

adobeflashplayerplugin.sls
Updated adobeflashplayerplugin.sls to v 18.0.0.194
=> Update adobeflashplayerplugin.sls to v 18.0.0.194

adobeflashplayeractivex.sls
Updated adobeflashplayeractivex.sls to v 18.0.0.194
=> Update adobeflashplayeractivex.sls to v 18.0.0.194

ccleaner.sls
Updated ccleaner.sls to ver. 5.07
=> Update ccleaner.sls to ver. 5.07

firefox.sls
Updated firefox.sls to ver. 38.0.5 and 38.0.6
=> Update firefox.sls to ver. 38.0.6

winscp.sls
Updated winscp.sls to ver. 5.7.4
=> Update winscp.sls to ver. 5.7.4

npp.sls
Updated npp.sls to ver. 6.7.9.2
=> Update npp.sls to ver. 6.7.9.2

adobeair.sls
Created adobeair.sls ver. 18.0.0.144
=> Create adobeair.sls ver. 18.0.0.144

adobereader_dc-mui.sls
Created adobereader_dc-mui.sls ver. 2015.007.20033
=> Create adobereader_dc-mui.sls ver. 2015.007.20033

autopsy.sls
Updated autopsy.sls to ver. 3.1.3
=> Update autopsy.sls to ver. 3.1.3

autohotkey.sls
Updated autohotkey.sls to ver. 1.1.22.02
=> Update autohotkey.sls to ver. 1.1.22.02

filezilla.sls
Updated filezilla.sls to ver. 3.11.0.2
=> Update filezilla.sls to ver. 3.11.0.2

firefox.sls
Updated firefox.sls to ver. 39.0
=> Update firefox.sls to ver. 39.0

blender.sls
Updated blender.sls to ver. 2.75
=> Update blender.sls to ver. 2.75

gpg4win.sls
Updated gpg4win.sls to ver. 2.2.4
=> Update gpg4win.sls to ver. 2.2.4

gpg4win-light.sls
Updated gpg4win-light.sls to ver. 2.2.4
=> Update gpg4win-light.sls to ver. 2.2.4

gpg4win-vanilla.sls
Updated gpg4win-vanilla.sls to ver. 2.2.4
=> Update gpg4win-vanilla.sls to ver. 2.2.4

ms-vcpp-2013-redist_x86.sls
Created ms-vcpp-2013-redist_x86.sls ver. 12.0.30501
=> Create ms-vcpp-2013-redist_x86.sls ver. 12.0.30501

ms-vcpp-2013-redist.sls
Created ms-vcpp-2013-redist.sls ver. 12.0.30501
=> Create ms-vcpp-2013-redist.sls ver. 12.0.30501

curl.sls
Updated curl.sls to ver. 7.43.0
=> Update curl.sls to ver. 7.43.0

adobeflashplayerplugin.sls
Updated adobeflashplayerplugin.sls to ver. 18.0.0.203
=> Update adobeflashplayerplugin.sls to ver. 18.0.0.203

adobeflashplayeractivex.sls
Updated adobeflashplayeractivex.sls to ver. 18.0.0.203
=> Update adobeflashplayeractivex.sls to ver. 18.0.0.203

fciv.sls
need to install the readme.txt as well on un-install
=> Improve fciv.sls

windirstat.sls
Corrected windirstat.sls full_name, the old name was not recognized as the software being installed
=> Correct windirstat.sls full_name

autopsy.sls
Corrected autopsy.sls - fixed pkg name -> lowercase
=> Correct autopsy.sls - fixed pkg name -> lowercase

quicktime.sls
Created initial quicktime.sls ver. 7.77.80.95
=> Create initial quicktime.sls ver. 7.77.80.95

emet.sls
Updated emet.sls to ver. 5.2 and changed un-installer method
=> Update emet.sls to ver. 5.2 and changed un-installer method

curl_x86.sls
Created initial curl_x86.sls ver. 7.43.0
=> Create initial curl_x86.sls ver. 7.43.0

firefox.sls
all other pkgs are all lowercase, so I lowercased firefox as well
=> Improve firefox.sls make pkg name lowercase

irfanview_x86.sls
Created initial irfanview_x86.sls ver. 4.38
=> Create initial irfanview_x86.sls ver. 4.38

irfanview.sls
Corrected irfanview.sls ver. 4.38 - fixed full_name
=> Correct irfanview.sls ver. 4.38 - fixed full_name

adobeshockwaveplayer.sls
Created initial adobeshockwaveplayer.sls ver. 12.1.8.158
=> Create initial adobeshockwaveplayer.sls ver. 12.1.8.158

truecrypt_x86.sls
Created initial truecrypt_x86.sls ver. 7.1a
=> Create initial truecrypt_x86.sls ver. 7.1a

vlc.sls
Updated vlc.sls to ver. 2.2.1, and removed all earlier versions, as they can't be disambiguated by comparing the windows name string full_name.
=> Update vlc.sls to ver. 2.2.1

vlc_x86.sls
Created initial vlc_x86.sls ver. 2.2.1
=> Create initial vlc_x86.sls ver. 2.2.1

putty_x86.sls
Created initial putty_x86.sls ver. 0.62 0.62 0.63
=> Create initial putty_x86.sls ver. 0.62 0.62 0.63

7zip_x86.sls
Created initial 7zip_x86.sls ver. 9.20.00.0
=> Create initial 7zip_x86.sls ver. 9.20.00.0

7zip_beta.sls
Created initial 7zip_beta.sls ver. 15.05
=> Create initial 7zip_beta.sls ver. 15.05

7zip_beta_x86.sls
Created initial 7zip_beta_x86.sls ver. 15.05
=> Create initial 7zip_beta_x86.sls ver. 15.05

7zip.sls
Swapped out bad sourceforge mirror for 7zip ver. 9.20.00.0
=> Swap out bad sourceforge mirror for 7zip ver. 9.20.00.0

adobeflashplayeractivex.sls
Updated adobeflashplayeractivex.sls to ver. 18.0.0.209
=> Update adobeflashplayeractivex.sls to ver. 18.0.0.209

adobeflashplayerplugin.sls
Updated adobeflashplayerplugin.sls to ver. 18.0.0.209
=> Update adobeflashplayerplugin.sls to ver. 18.0.0.209

itunes.sls
Created initial itunes.sls ver. 12.2.1.16
=> Create initial itunes.sls ver. 12.2.1.16

itunes_x86.sls
Created initial itunes_x86.sls ver. 12.2.1.16
=> Create initial itunes_x86.sls ver. 12.2.1.16

adobeshockwaveplayer.sls
Updated adobeshockwaveplayer.sls to ver. 12.1.9.159
=> Update adobeshockwaveplayer.sls to ver. 12.1.9.159

chrome.sls
Updated chrome.sls to ver. 66.77.16518
=> Update chrome.sls to ver. 66.77.16518

chrome.sls
Swapped order of entries in chrome.sls
=> Swap order of entries in chrome.sls

cdroller.sls
fixe case to lowercase for cdroller
=> fix case for cdroller.sls

emet.sls
fixed case of emet.sls pkg name to lowercase
=> fix case of emet.sls pkg name to lowercase

putty.sls
Cleaned up putty.sls file , no reason to have old unsecure versions around.
=> Clean up putty.sls file

teamviewer.sls
Updated teamviewer.sls to ver. 10.0.43879
=> Update teamviewer.sls to ver. 10.0.43879

npp_x86.sls
Created initial npp_x86.sls ver. 6.7.9.2
=> Create initial npp_x86.sls ver. 6.7.9.2

winscp_x86.sls
Created initial winscp_x86.sls ver. 5.7.4
=> Create initial winscp_x86.sls ver. 5.7.4

npp_x86.sls
=> fix name of pkg npp_x86

windirstat_x86.sls
Create initial windirstat.sls ver. 1.1.2
=> Create initial windirstat.sls ver. 1.1.2

firefox_x86.sls
Created intial firefox_x86.sls ver. 39.0
=> Create intial firefox_x86.sls ver. 39.0

windirstat.sls
Swapped out bad sourceforge mirror for windirstat to a mirror
=> Swap out bad sourceforge mirror for windirstat to a mirror

windirstat_x86.sls
Swapped out bad sourceforge mirror for windirstat_x86.sls to a mirror
=> Swap out bad sourceforge mirror for windirstat_x86.sls to a mirror

keepass.sls
Created initial keepass.sls ver. 1.29
=> Create initial keepass.sls ver. 1.29

keepass-2x.sls
Created initial keepass-2x.sls ver. 2.29
=> Create initial keepass-2x.sls ver. 2.29

adobereader-xi.sls
Created initial adobereader-xi.sls ver. 11.0.6 + 11.0.10
=> Create initial adobereader-xi.sls ver. 11.0.6 + 11.0.10

adobereader-dc.sls
Created initial adobereader-dc.sls ver. 2015.008.20082
=> Create initial adobereader-dc.sls ver. 2015.008.20082

jre.sls
Removed jre_x86 contents from jre.sls file
=> Removed jre_x86 contents from jre.sls file

jre_x86.sls
Create intial jre_x86.sls from what was in jre.sls
=> Create intial jre_x86.sls from what was in jre.sls

jre.sls
Updated jre.sls to ver. 7.0.790
```
Note: 
due to winrepo installer limitations you need to manually download the exe from
http://javadl.sun.com/webapps/download/AutoDL?BundleId=106369
and put it on the winrepo on master to install it the 'salt://win/repo/jre/... way
```
=> Update jre.sls to ver. 7.0.790

jre_x86.sls
Updated jre_x86.sls to ver. 7.0.790
=> Update jre_x86.sls to ver. 7.0.790

jre.sls
added jre missing un-installer
=> add jre missing un-installer

jre_x86.sls
Fixed jre_x86 un-installer section
=> Fix jre_x86 un-installer section

jre8.sls
Created initial jre8.sls ver 8.0.450
=> Create initial jre8.sls ver 8.0.450

jre8_x86.sls
Created initial jre8_x86.sls ver 8.0.450
=> Create initial jre8_x86.sls ver 8.0.450

jre8.sls
Updated jre8.sls to ver. 8.0.510
=> Update jre8.sls to ver. 8.0.510

jre8_x86.sls
Updated jre8_x86.sls to ver. 8.0.510
=> Update jre8_x86.sls to ver. 8.0.510

wireshark.sls
Update wireshark.sls to stable 1.12.6 and devel 1.99.7
=> Update wireshark.sls to stable 1.12.6 and devel 1.99.7

wireshark_x86.sls
Created initial wireshark_x86.sls ver. 1.12.6
=> Create initial wireshark_x86.sls ver. 1.12.6

wireshark-devel_x86.sls
Created initial wireshark-devel_x86.sls ver. 1.99.7
=> Create initial wireshark-devel_x86.sls ver. 1.99.7

wireshark_x86.sls
Fixed download URL for wireshark_x86 stable v 1.12.6
=> Fix download URL for wireshark_x86 stable v 1.12.6

teracopy.sls
Created initial teracopy.sls ver. 2.3
=> Create initial teracopy.sls ver. 2.3

teracopy_x86.sls
Created initial teracopy_x86.sls ver. 2.3
=> Create initial teracopy_x86.sls ver. 2.3

clink.sls
Created initial clink.sls ver. 0.4.3 & 0.4.4
=> Create initial clink.sls ver. 0.4.3 & 0.4.4

clink_x86.sls
Created initial clink_x86.sls ver. 0.4.3 & 0.4.4
=> Create initial clink_x86.sls ver. 0.4.3 & 0.4.4

clink.sls, clink_x86.sls
Swapped clink from local to internet installer
=> Swap clink from local to internet installer

chrome.sls
Swap chrome entry order back and remove duplicate pkg name
=> Swap chrome entry order back and remove duplicate pkg name

conemu-preview.sls
Created initial conemu-preview.sls ver. 11.150.7050
=> Create initial conemu-preview.sls ver. 11.150.7050

conemu-preview_x86.sls
Created initial conemu-preview_x86.sls ver. 11.150.7050
=> Create initial conemu-preview_x86.sls ver. 11.150.7050

conemu-preview.sls
Fixed silent flag in conemu-preview.sls
=> Fix silent flag in conemu-preview.sls

conemu-alpha.sls
Created initial conemu-alpha.sls ver. 11.150.7160
=> Create initial conemu-alpha.sls ver. 11.150.7160

conemu-alpha_x86.sls
Created initial conemu-alpha_x86.sls ver. 11.150.7160
=> Create initial conemu-alpha_x86.sls ver. 11.150.7160

windirstat.sls, windirstat_x86.sls
Add missing ver number to Uninstaller reg key
=> The big bear add missing ver to windirstat

chocolatey.sls
Created initial chocolatey.sls ver. 0.9.8
=> Create initial chocolatey.sls ver. 0.9.8

wireshark-devel.sls, wireshark.sls
Split into wireshark.sls (stable) and wireshark-devel.sls (devel)
=> Split into wireshark.sls and wireshark-devel.sls

icloud.sls
Created initial icloud.sls ver. 4.1.1.53
=> Create initial icloud.sls ver. 4.1.1.53

clamwin.sls
fixed clamwin.sls case to lowercase
=> fix clamwin.sls case to lowercase

internet-evidence-finder.sls
fix case in internet-evidence-finder.sls pkg name to all lowercase
@dkarpo dkarpo@gmail.com are you OK with this pkg name to be all lowercased ?
=> fix case in internet-evidence-finder.sls pkg name to all lowercase

windirstat.sls
Reverts saltstack/salt-winrepo#343 this was not yet ready - sorry
=> Revert "Update windirstat.sls"

gpu-z.sls
Update gpu-z.sls to ver. 0.8.2
=> Update gpu-z.sls to ver. 0.8.2

gpu-z.sls
Updated gpu-z.sls to ver. 0.8.3
=> Update gpu-z.sls to ver. 0.8.3

gpu-z.sls
Updated gpu-z.sls to ver. 0.8.4
=> Update gpu-z.sls to ver. 0.8.4

sandboxie.sls
Created initial sandboxie.sls ver. 4.20
=> Create initial sandboxie.sls ver. 4.20

rdcman.sls
Remote Desktop Connection Manager package definition.
=> Add rdcman

fiddler.sls
Fiddler web debugging proxy package definition.
=> Create initial fiddler.sls

fiddler_x86.sls
Created initial fiddler_x86 ver. 2.5.1.2 + 4.5.1.4
=> Create initial fiddler_x86 ver. 2.5.1.2 + 4.5.1.4

fiddler.sls
Force inst dir for Fiddler v 2 and v 4 to be Fiddler
=> Force inst dir for Fiddler v 2 and v 4 to be Fiddler

salt-minion.sls, salt-minion_x86.sls
Update salt-minion to ver. 2015.8.0rc2
=> Update salt-minion.sls to ver. 2015.8.0rc2

openvpn.sls, openvpn_x86.sls
Create initial openvpn.sls v. 2.3.6
=> Create initial openvpn.sls v. 2.3.6

curl.sls, curl_x86.sls
=> Fix curl uninstallers

adobeair.sls, adobeflashplayeractivex.sls, adobeflashplayerplugin.sls, adobereader-dc.sls, autopsy.sls, inkscape.sls, libreoffice.sls, ms-vcpp-2008-redist.sls, ms-vcpp-2008-redist_x86.sls, ms-vcpp-2008-sp1-atl-redist.sls, ms-vcpp-2008-sp1-atl-redist_x86.sls, ms-vcpp-2008-sp1-mfc-redist.sls, ms-vcpp-2008-sp1-mfc-redist_x86.sls, ms-vcpp-2010-sp1-mfc-redist.sls, ms-vcpp-2010-sp1-mfc-redist_x86.sls, mysql-essential.sls, mysql-installer-community.sls, openoffice.sls, pdf24creator.sls, realvnc.sls, skype-msi.sls, svn.sls, tightvnc.sls, tightvnc_x86.sls, tortoise-git.sls, tortoise-git_x86.sls, tortoise-hg.sls, tortoise-hg_x86.sls, tortoise-svn.sls, tortoise-svn_x86.sls
Fix 32 wrong msiexec.exe un-installer stanzas (2 of which for curl were fixed in separate commit TheBigBear@5794335d743b47ba5db610ed838a324fd58e0135)
=> Fix adobeair.sls msiexec.exe uninstaller stanzas

adobereader-dc.sls, openoffice.sls
=> Add missing msiexec true lines

adobereader-xi.sls, adobeshockwaveplayer.sls, chrome.sls, conemu-alpha.sls, conemu-alpha_x86.sls, conemu-preview.sls, conemu-preview_x86.sls, emet.sls, icloud.sls, itunes.sls, itunes_x86.sls, jre.sls, jre8.sls, jre8_x86.sls, jre_x86.sls, keepass-2x.sls, keepass.sls
Fix wrong 'msiexec.exe' un-installer stanzas (2nd run)
=> Fix wrong 'msiexec.exe' un-installer stanzas (2nd run)

chrome.sls
Update chrome to ver. 66.88.49277
=> Update chrome to ver. 66.88.49277

keepass.sls
Fixed pkg name keepass ver. 1.x
=> Fix pkg name keepass v. 1.x

xming.sls, xming_x86.sls
=> Create initial xming.sls ver. 6.9.0.31

npp.sls, npp_x86.sls
=> Update npp to ver. 6.8.1

chromedl.sls
Updated un-installer switch to prevent reboot on un-install
=> Update un-installer switch to prevent reboot

ms-vcpp-2008-sp1-atl-redist_x86.sls
Fixed ms-vcpp-2008-sp1-atl-redist_x86 ver no
=> Fix ms-vcpp-2008-sp1-atl-redist_x86 ver no

ms-vcpp-2008-sp1-mfc-redist.sls, ms-vcpp-2008-sp1-mfc-redist_x86.sls
Fixed URL for ms-vcpp-2008-sp1-mfc-redist
=> Fix URL for ms-vcpp-2008-sp1-mfc-redist

adobereader-xi.sls
=> Fix pkg name adobereader-xi

salt-minion.sls, salt-minion_x86.sls
Updated salt-minion to ver. 2015.8.0rc3
=> Update salt-minion to ver. 2015.8.0rc3

salt-minion.sls, salt-minion_x86.sls
Swapped out DL URLs of salt-minion -> wpengine.com
=> Swap out DL URLs salt-minion -> wpengine.com 

salt-minion.sls, salt-minion_x86.sls
Moved salt-minion to new website repo.saltstack.com
=> Move salt-minion to new website repo.saltstack.com 

itunes_x86.sls
Fixed minor error itunes_x86.sls mistyping
=> Fix minor error itunes_x86.sls mistyping

openvpn.sls
=> Fix indent error in openvpn

openvpn.sls
Fixed another indent problem in openvpn.sls
=> Fix another indent problem in openvpn.sls

firefox.sls, firefox_x86.sls
Updated firefox.sls ver. 39.0.3
=> Update firefox.sls ver. 39.0.3

firefox.sls, firefox_x86.sls, openvpn.sls
Updated firefox to ver. 39.0.3
=> Update firefox to ver. 39.0.3

putty.sls, putty_x86.sls
=> Fix putty un-install string

adobeair.sls
Fixed adobeair.sls un-installer
=> Fix adobeair.sls un-installer

logparser.sls
Microsoft Log Parser 2.2.10
https://technet.microsoft.com/en-us/scriptcenter/dd919274.aspx
https://www.microsoft.com/en-us/download/details.aspx?id=24659
=> Create initial logparser.sls 2.2.10

advancedlogging.sls
Microsoft IIS Advanced Logging 1.0
=> Create initial advancedlogging.sls ver 1.0.0625.10

urlrewrite.sls
Microsoft IIS URL Rewrite Module 2
=> Create initial urlrewrite.sls ver 7.2.1952

webdeploy.sls
=> Create initial webdeploy.sls ver 3.1237.1764

sensu.sls
Added [sensu client ](https://sensuapp.org/docs/latest/windows-msi-install), unfortunately the service needs to be enabled afterwards, the installer does not automatically create one
=> Added sensu client

winhttpcertcfg.sls
Microsoft Windows HTTP Services certificate configuration tool
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384088(v=vs.85).aspx
=> Create initial winhttpcertcfg.sls ver 5.2.3790.1060

intellij.sls, vagrant.sls
=> Remove /i flags

isapirewrite-lite.sls
ISAPI_Rewrite 3 - Apache .htaccess mod_rewrite compatible module for IIS
http://www.helicontech.com/isapi_rewrite/
http://www.helicontech.com/isapi_rewrite/download.html
=> Create initial isapirewrite-lite.sls ver. 3.1.0112

urlrewrite.sls
Adding support for URL Rewrite version 7.1.0490.43.
=> Add ver. 7.1.0490.43 to urlrewrite.sls

stunnel.sls, stunnel_x86.sls
Stunnel is a proxy designed to add TLS encryption functionality to existing clients and servers without any changes in the programs' code. Its architecture is optimized for security, portability, and scalability (including load-balancing), making it suitable for large deployments.
https://www.stunnel.org/downloads.html
=> Create initial stunnel.sls and stunnel_x86.sls ver. 'Not Found'

iismediaservices.sls
IIS Media Services, an integrated HTTP-based media delivery platform, delivers true HD (720p+) live and on-demand streaming, DVR functionality, and real-time analytics support to computers, TVs, and mobile devices. 
http://www.iis.net/learn/media/on-demand-smooth-streaming/getting-started-with-iis-smooth-streaming
=> Create initial iismediaservices.sls ver. 4.1.0938.454

slack.sls
Per discussion in #499 
Note: **THIS DOES NOT FIX 499**
=> Fix slack download link

cpu-z.sls, libreoffice.sls
Additionally removes local download link, as a working download link is available nowadays
=> Updates cpu-z to 1.73.0

salt-minion.sls, salt-minion_x86.sls
Replaced the 2015.8.0 release with 2015.8.0-3
The previous releases of 2015.8.0 will be moved to the Archive directory
=> Added the -3 release for 2015.8.0

salt-minion.sls, salt-minion_x86.sls
the version number and the the version in full_name are actually 2015.8.0-3 for this minon the winrepo-ng is good but this one was not.
=> Fix salt-minion full_name and version to match

jre.sls, jre_x86.sls
Oracle have removed all but the latest old jre downloads
=> Removed old jre version

ossec-agent.sls
Adds support for the OSSEC agent using a salt:// path. The official download page for the OSSEC agent is http://www.ossec.net/?page_id=19
=> Add support for the OSSEC agent

wireshark_x86.sls
fixes https://github.com/saltstack/salt-winrepo/pull/648/files#r48512781
=> Fix version number wireshark_x86.sls

cyberduck.sls, cyberduck_x86.sls
Cyberduck -> Libre FTP, SFTP, WebDAV, S3, Azure & OpenStack Swift browser for Mac and Windows.
https://cyberduck.io/?l=en
=> Create initial cyberduck.sls 4.7.3

messageanalyzer.sls, messageanalyzer_x86.sls
Microsoft Message Analyzer is a new tool for capturing, displaying, and analyzing protocol messaging traffic, events, and other system or application messages in network troubleshooting and other diagnostic scenarios. Message Analyzer also enables you to load, aggregate, and analyze data from log and saved trace files.
https://www.microsoft.com/en-us/download/details.aspx?id=44226
https://technet.microsoft.com/en-us/library/jj649776.aspx
=> Create initial messageanalyzer.sls 4.0.7551.0

nsclient.sls, nsclient_x86.sls
The package is now available for download from github.
=> Fix / add nsclient DL URL

postgresql.sls, postgresql_x86.sls
PostgreSQL: The world's most advanced open source database.
http://www.postgresql.org/
Tested on Windows 7 Professional x64, running salt-minion 2014.7.1
=> Create initial postgresql.sls and postgresql_x86.sls

applicationrequestrouting.sls
IIS Application Request Routing enables Web server administrators, hosting providers, and Content Delivery Networks to increase Web application scalability and reliability through rule-based routing, client and host name affinity, load balancing of HTTP server requests, and distributed disk caching.
http://www.iis.net/downloads/microsoft/application-request-routing
=> Create initial applicationrequestrouting.sls 3.0.1952

sensu.sls
Same as https://github.com/saltstack/salt-winrepo-ng/pull/295
=> updated to sensu 21.0.1

ultradefrag.sls, ultradefrag_x86.sls
**Changes**
* Update ultradefrag to current/stable 7.0.0 version.
* See http://ultradefrag.sourceforge.net/en/index.html
**Testing**
* Tested on Windows 2012r2 running salt-minion 2015.5.9.
=> Update ultradefrag to 7.0.0

ice.sls
Ice is a comprehensive RPC framework with support for C++, C#, Java, JavaScript, Python, and more.
https://zeroc.com/products/ice
Tested on Windows 2012r2.
=> Create initial ZeroC Ice 3.6.1.2

qemu.sls, qemu_x86.sls
QEMU for Windows. QEMU is a generic and open source machine emulator and virtualizer.
http://qemu.weilnetz.de/
Tested install on Windows 2012r2.
=> Create initial QEMU 2.5.50

octopus-tentacle.sls, octopus-tentacle_x86.sls
Octopus is a friendly deployment automation tool for .NET developers.
https://octopus.com/downloads
=> Add initial Octopus Deploy Tentacle 3.3.17

octopus-tentacle.sls, octopus-tentacle_x86.sls
**Changes**
* Updated Octopus Tentacle definitions to include latest version via the relevant URIs.
**Testing**
* None.
=> Add latest to Octopus Tentacle definition
